@baseUrl = https://photoslibrary.googleapis.com
@APIKey = {{$dotenv GOOGLEPHOTO_API_KEY}}
@ClientID = {{$dotenv GOOGLE_CLIENT_ID}}
@Secret = {{$dotenv GOOGLE_SECRET}}

###

### https://developers.google.com/identity/protocols/oauth2/limited-input-device

###

# @name deviceAndUserCode
POST https://oauth2.googleapis.com/device/code HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id={{ClientID}}&scope=email%20profile

### 

@Code = {{deviceAndUserCode.response.body.device_code}}

###

# @name getAuthToken
POST https://oauth2.googleapis.com/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id={{ClientID}}&client_secret={{Secret}}&device_code={{Code}}&grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code

###

@authToken = {{getAuthToken.response.body.access_token}}
@refreshToken = {{getAuthToken.response.body.refresh_token}}

###

# @name refreshAuthToken
POST https://oauth2.googleapis.com/token HTTP/1.1
Host: oauth2.googleapis.com
Content-Type: application/x-www-form-urlencoded

client_id={{ClientID}}&client_secret={{Secret}}&refresh_token={{refreshToken}}&grant_type=refresh_token


###

# @authToken = {{refreshAuthToken.response.body.access_token}}

###

# @name revokeAuthToken
POST https://oauth2.googleapis.com/revoke/?token={{authToken}} HTTP/1.1
Content-Type: application/x-www-form-urlencoded

###

# @name newSession
POST https://photospicker.googleapis.com/v1/sessions
content-type: application/json
authorization: Bearer {{authToken}}

###

@sessionId = {{newSession.response.body.id}}

###

# @name get
GET https://photospicker.googleapis.com/v1/mediaItems?sessionId={{sessionId}}&pageSize=25
content-type: application/json
authorization: Bearer {{authToken}}

###



###

POST https://photospicker.googleapis.com/v1/mediaItems
content-type: application/json
authorization: Bearer {{authToken}}
accept: application/json

{
  "pageSize": 100,
  "filters": {
    "dateFilter": {
        "dates": [],
        "ranges": [
            {
                "startDate": {
                    "year": 2023,
                    "month": 1,
                    "day": 1
                },
                "endDate": {
                    "year": 2023,
                    "month": 5,
                    "day": 1
                }
            }
        ]
    },
  },
}
###

# @name get
GET {{baseUrl}}/v1/albums?pageSize=5
content-type: application/json
authorization: Bearer {{authToken}}

{
    "message": "test warn"
}

###
